language: cpp
compiler: gcc

addons:
    # Install lcov for codecoverage
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - lcov

before_install:
    # Install CMake 3.10 and hack $PATH to use it
    - mkdir $HOME/usr
    - export PATH="$HOME/usr/bin:$PATH"
    - wget https://cmake.org/files/v3.10/cmake-3.10.1-Linux-x86_64.sh
    - chmod +x cmake-3.10.1-Linux-x86_64.sh
    - ./cmake-3.10.1-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license
    # Install Qt5.9
    - sudo add-apt-repository --yes ppa:beineri/opt-qt591-trusty
    - sudo apt-get update -qq
    - sudo apt-get install qt59base qtbase5-dev

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3

script:
    - source /opt/qt59/bin/qt59-env.sh
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ctest -V

after_success:
        # Creating report
        - cd ${TRAVIS_BUILD_DIR}
        - lcov --directory . --capture --output-file coverage.info # capture coverage info
        - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
        - lcov --list coverage.info #debug info
        # Uploading report to CodeCov
        - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
