language: cpp

before_install:
    - mkdir $HOME/usr
    - export PATH="$HOME/usr/bin:$PATH"
    - wget https://cmake.org/files/v3.10/cmake-3.10.1-Linux-x86_64.sh
    - chmod +x cmake-3.10.1-Linux-x86_64.sh
    - ./cmake-3.10.1-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - ctest

compiler:
    - clang
    - gcc
