language: cpp

before_install:
    - mkdir $HOME/usr
    - export PATH="$HOME/usr/bin:$PATH"
    - wget https://cmake.org/files/v3.10/cmake-3.10.1-Linux-x86_64.sh
    - chmod +x cmake-3.10.1-Linux-x86_64.sh
    - ./cmake-3.10.1-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license
    - sudo add-apt-repository --yes ppa:beineri/opt-qt591-trusty
    - sudo apt-get update -qq
    - sudo apt-get install qt59base qtbase5-dev

script:
    - source /opt/qt59/bin/qt59-env.sh
    - mkdir build
    - cd build
    - cmake ..
    - make
    - install/bin/test_geometry
    - ctest

compiler:
    - clang
    - gcc
